import type { strings } from './strings';

export const stringsEn: Record<keyof typeof strings, string> = {
  app_name: 'QQ Browser',
  tab_feed: 'Feed',
  tab_novel: 'Novels',
  tab_home: 'Home',
  tab_files: 'Files',
  tab_me: 'Me',
  weather_temp: '29°',
  weather_city: 'Shenzhen',
  search_placeholder: 'Search Web, Pages & Hot List',
  search_btn: 'Search',
  tool_files: 'Files',
  tool_novel: 'Novels',
  tool_video: 'Videos',
  tool_drama: 'Hot Dramas',
  tool_bookmarks: 'Bookmarks',
  tool_scan: 'Scan',
  tool_sogou: 'Sogou Search',
  tool_deepseek: 'DeepSeek',
  qbot_greeting: 'Hi, I am QBot AI Assistant for web search & deep thinking',
  feed_title: 'Recommended · Hot Topics',
  feed_ch_all: 'For You',
  feed_ch_hot: 'Hot List',
  feed_ch_video: 'Videos',
  feed_ch_tech: 'Tech',
  novel_title: 'Free Novels · Bookshelf',
  novel_shelf_tab: 'Bookshelf',
  novel_rank_tab: 'Bookstore',
  novel_in_shelf: 'In Shelf',
  novel_add_shelf: 'Add to Shelf',
  files_title: 'File Manager · Cloud Drive',
  files_storage_used: 'Used 12.4 GB / 100 GB Cloud Space',
  files_cat_all: 'All Files',
  files_cat_doc: 'Documents',
  files_cat_media: 'Media',
  files_fav_only: 'Starred Only',
  me_bookmarks_title: 'Bookmarks',
  me_history_title: 'History',
  me_downloads_title: 'Downloads',
  me_tabs_title: 'Open Tabs',
  me_qbot_card: 'QBot · DeepSeek R1 Full Line',
  me_qbot_sub: 'Unlimited AI web search, page summary & doc reader',
  article_title: 'Web Page',
  article_bookmark: 'Bookmark',
  article_bookmarked: 'Bookmarked',
  article_like: 'Like',
  article_liked: 'Liked',
  article_comment_placeholder: 'Write a comment...',
  article_comment_send: 'Post',
  search_history_title: 'Search History',
  search_hot_title: 'Trending Searches',
  search_clear: 'Clear',
  search_no_results: 'No matching web pages or articles found',
};
