export const strings = {
  app_name: 'QQ浏览器',
  tab_feed: '推荐',
  tab_novel: '小说',
  tab_home: '首页',
  tab_files: '文件',
  tab_me: '我的',
  weather_temp: '29°',
  weather_city: '深圳',
  search_placeholder: '搜全网 看网页 看热榜',
  search_btn: '搜索',
  tool_files: '文件',
  tool_novel: '小说',
  tool_video: '视频',
  tool_drama: '热搜好剧',
  tool_bookmarks: '书签收藏',
  tool_scan: '扫码',
  tool_sogou: '搜狗搜索',
  tool_deepseek: 'DeepSeek',
  qbot_greeting: '你好，我是 QBot 智能助手，支持全网搜索与深度思考',
  feed_title: '推荐资讯 · 全网热榜',
  feed_ch_all: '综合推荐',
  feed_ch_hot: '全网热榜',
  feed_ch_video: '热门视频',
  feed_ch_tech: '科技数码',
  novel_title: '免费小说 · 书架',
  novel_shelf_tab: '我的书架',
  novel_rank_tab: '爆款书城',
  novel_in_shelf: '已在书架',
  novel_add_shelf: '加入书架',
  files_title: '文件管理 · 云盘',
  files_storage_used: '已用 12.4 GB / 100 GB 免费云空间',
  files_cat_all: '全部文件',
  files_cat_doc: '文档',
  files_cat_media: '视频图片',
  files_fav_only: '仅看星标',
  me_bookmarks_title: '书签收藏',
  me_history_title: '浏览历史',
  me_downloads_title: '下载管理',
  me_tabs_title: '多窗口标签页',
  me_qbot_card: 'QBot · DeepSeek 满血版专线',
  me_qbot_sub: '免费无限次 AI 搜索、总结网页与文档解读',
  article_title: '网页正文',
  article_bookmark: '收藏书签',
  article_bookmarked: '已收藏',
  article_like: '点赞',
  article_liked: '已赞',
  article_comment_placeholder: '发表你的看法...',
  article_comment_send: '发布',
  search_history_title: '搜索历史',
  search_hot_title: '全网热搜榜',
  search_clear: '清空',
  search_no_results: '未找到相关网页或资讯，换个关键词试试',
} as const;
