export const strings = {
  app_name: '百度网盘',
  tab_home: '首页',
  tab_files: '文件',
  tab_kuku_ai: '库库AI',
  tab_share: '共享',
  tab_me: '我的',
  search_placeholder: '文件搜索',
  search_btn: '搜索',
  kk_album: '相册',
  kk_novel: '小说',
  kk_scan: '扫描',
  kk_note: '听记',
  kk_drama: '短剧',
  sec_recent: '最近',
  sec_transfer: '转存记录',
  sec_subscribe: '订阅更新',
  sec_memory: '回忆',
  badge_new: '新',
  privacy_hidden_hint: '已开启隐私保护，点击眼睛图标恢复显示',
  files_title: '全部文件',
  files_cat_all: '全部',
  files_cat_transfer: '转存',
  files_cat_album: '相册',
  files_cat_scan: '扫描',
  files_cat_starred: '星标',
  ai_title: '库库AI · 云端智能助理',
  ai_subtitle: '懂你所需的网盘AI管家',
  ai_clear: '清空对话',
  ai_quick_prompts: '猜你想问',
  share_title: '共享空间',
  share_mark_all_read: '全部已读',
  detail_title: '文件详情',
  detail_size: '文件大小',
  detail_time: '修改时间',
  detail_location: '存储位置',
  detail_star: '星标收藏',
  detail_starred: '已星标',
  detail_download: '高速下载',
  detail_downloaded: '已加入传输列表',
  detail_ask_ai: '用库库AI解读此文件',
  search_history_title: '历史搜索',
  search_discover_title: '热门网盘搜索',
  search_clear: '清空',
  search_no_results: '未找到匹配的网盘文件',
  me_cloud_space: '网盘云端容量',
  me_svip_title: 'SVIP 超级会员中心',
  me_svip_sub: '尊享 12TB 超大空间 · 极速下载特权',
  me_stat_files: '全部文件',
  me_stat_starred: '星标文件',
  me_stat_transfer: '传输完成',
  me_stat_album: '云端照片',
} as const;
