import type { strings } from './strings';

export const stringsEn: Record<keyof typeof strings, string> = {
  app_name: 'Baidu Netdisk',
  tab_home: 'Home',
  tab_files: 'Files',
  tab_kuku_ai: 'Kuku AI',
  tab_share: 'Share',
  tab_me: 'Me',
  search_placeholder: 'Search files',
  search_btn: 'Search',
  kk_album: 'Albums',
  kk_novel: 'Novels',
  kk_scan: 'Scanner',
  kk_note: 'Notes',
  kk_drama: 'Dramas',
  sec_recent: 'Recent',
  sec_transfer: 'Saved Files',
  sec_subscribe: 'Subscriptions',
  sec_memory: 'Memories',
  badge_new: 'NEW',
  privacy_hidden_hint: 'Privacy mode enabled. Tap the eye icon to reveal.',
  files_title: 'All Files',
  files_cat_all: 'All',
  files_cat_transfer: 'Saved',
  files_cat_album: 'Albums',
  files_cat_scan: 'Scans',
  files_cat_starred: 'Starred',
  ai_title: 'Kuku AI · Cloud Assistant',
  ai_subtitle: 'Your Smart Netdisk Companion',
  ai_clear: 'Clear Chat',
  ai_quick_prompts: 'Suggested Prompts',
  share_title: 'Shared Spaces',
  share_mark_all_read: 'Mark All Read',
  detail_title: 'File Details',
  detail_size: 'Size',
  detail_time: 'Modified',
  detail_location: 'Location',
  detail_star: 'Star',
  detail_starred: 'Starred',
  detail_download: 'Fast Download',
  detail_downloaded: 'Added to Transfers',
  detail_ask_ai: 'Analyze with Kuku AI',
  search_history_title: 'Search History',
  search_discover_title: 'Trending Searches',
  search_clear: 'Clear',
  search_no_results: 'No matching files found',
  me_cloud_space: 'Cloud Storage',
  me_svip_title: 'SVIP Membership Center',
  me_svip_sub: '12TB Storage · Ultra-Fast Downloads',
  me_stat_files: 'All Files',
  me_stat_starred: 'Starred',
  me_stat_transfer: 'Transferred',
  me_stat_album: 'Cloud Photos',
};
