import type { strings } from './strings';

export const stringsEn: Record<keyof typeof strings, string> = {
  app_name: 'Taobao',
  tab_home: 'Home',
  tab_video: 'Video',
  tab_message: 'Messages',
  tab_cart: 'Cart',
  tab_me: 'My Taobao',
  ch_follow: 'Follow',
  ch_recommend: 'For You',
  ch_flash: 'Flash',
  ch_subsidy: 'Subsidy',
  ch_fliggy: 'Fliggy',
  ch_national: 'Holiday Sale',
  ch_outfit: 'Style',
  search_placeholder: 'Custom Mechanical Keyboard',
  search_btn: 'Search',
  kk_tmall_new: 'Tmall New',
  kk_daily_cash: 'Daily Cash',
  kk_baba_farm: 'Baba Farm',
  kk_topup: 'Top-up',
  kk_88vip: '88VIP',
  kk_taocoins: 'Tao Coins',
  card_live_title: 'Taobao Live',
  card_live_sub: 'Top Streams',
  card_subsidy_title: '10B Subsidy',
  card_subsidy_sub: 'Best Price',
  card_seckill_title: 'Flash Deals',
  card_seckill_sub: 'Daily Low',
  promo_banner_text: 'Get ¥255 Coupon Pack',
  promo_banner_claimed: 'Claimed ¥255 Coupon Pack',
  promo_claim_btn: 'Claim Now',
  promo_claimed_btn: 'Claimed',
  return_insurance: 'Free Return',
  currency_symbol: '¥',
  search_history_title: 'Search History',
  search_discover_title: 'Discover',
  search_clear: 'Clear',
  search_no_results: 'No matching items found',
  detail_title: 'Item Detail',
  detail_guarantee: 'Authentic · Fast Refund · 7-Day Free Return',
  detail_shipping: 'Express: Free Shipping · Ships within 48h',
  detail_reviews_title: 'Reviews (99+)',
  detail_shop_enter: 'Visit Store',
  detail_all_goods: 'All Items',
  detail_shop: 'Store',
  detail_service: 'Support',
  detail_fav: 'Save',
  detail_faved: 'Saved',
  detail_add_cart: 'Add to Cart',
  detail_added_cart: 'Added',
  detail_buy_now: 'Buy Now',
  cart_title: 'Cart',
  cart_empty: 'Your cart is empty',
  cart_select_all: 'All',
  cart_total: 'Total:',
  cart_checkout: 'Checkout',
  cart_checked_out_toast: 'Order placed successfully!',
  msg_title: 'Messages',
  msg_sub_unread: 'All messages read',
  video_title: 'Taobao Video',
  video_follow_btn: 'Follow',
  video_followed_btn: 'Following',
  me_orders_title: 'My Orders',
  me_orders_all: 'All',
  me_order_unpaid: 'To Pay',
  me_order_unshipped: 'To Ship',
  me_order_shipped: 'To Receive',
  me_order_review: 'To Review',
  me_order_refund: 'Refunds',
  me_stat_fav: 'Favorites',
  me_stat_follow_shop: 'Stores',
  me_stat_footprint: 'History',
  me_stat_coupons: 'Coupons',
  me_vip_title: '88VIP · Exclusive Benefits',
  me_vip_sub: 'Daily Subsidies · 5% Off',
};
