export const strings = {
  app_name: '淘宝',
  tab_home: '首页',
  tab_video: '视频',
  tab_message: '消息',
  tab_cart: '购物车',
  tab_me: '我的淘宝',
  ch_follow: '关注',
  ch_recommend: '推荐',
  ch_flash: '闪购',
  ch_subsidy: '国补',
  ch_fliggy: '飞猪',
  ch_national: '国庆狂欢',
  ch_outfit: '穿搭',
  search_placeholder: '机械键盘客制化',
  search_btn: '搜索',
  kk_tmall_new: '天猫新品',
  kk_daily_cash: '天天领钱',
  kk_baba_farm: '芭芭农场',
  kk_topup: '充值中心',
  kk_88vip: '88VIP',
  kk_taocoins: '领淘金币',
  card_live_title: '淘宝直播',
  card_live_sub: '热门好播',
  card_subsidy_title: '百亿补贴',
  card_subsidy_sub: '买贵必赔',
  card_seckill_title: '淘宝秒杀',
  card_seckill_sub: '天天低价',
  promo_banner_text: '送你255元消费券包',
  promo_banner_claimed: '已领取255元消费券包',
  promo_claim_btn: '立即领取',
  promo_claimed_btn: '已领取',
  return_insurance: '退货宝',
  currency_symbol: '¥',
  search_history_title: '历史搜索',
  search_discover_title: '搜索发现',
  search_clear: '清空',
  search_no_results: '未找到相关宝贝，换个词试试吧',
  detail_title: '宝贝详情',
  detail_guarantee: '假一赔四 · 极速退款 · 七天无理由退换',
  detail_shipping: '快递: 免运费 · 预计48小时内发货',
  detail_reviews_title: '宝贝评价 (99+)',
  detail_shop_enter: '进店逛逛',
  detail_all_goods: '全部宝贝',
  detail_shop: '店铺',
  detail_service: '客服',
  detail_fav: '收藏',
  detail_faved: '已收藏',
  detail_add_cart: '加入购物车',
  detail_added_cart: '已加购',
  detail_buy_now: '立即购买',
  cart_title: '购物车',
  cart_empty: '购物车空空如也，去首页逛逛吧',
  cart_select_all: '全选',
  cart_total: '合计:',
  cart_checkout: '结算',
  cart_checked_out_toast: '订单提交成功！感谢购买',
  msg_title: '消息',
  msg_sub_unread: '全部消息已读',
  video_title: '淘宝视频 · 逛逛',
  video_follow_btn: '关注',
  video_followed_btn: '已关注',
  me_orders_title: '我的订单',
  me_orders_all: '全部',
  me_order_unpaid: '待付款',
  me_order_unshipped: '待发货',
  me_order_shipped: '待收货',
  me_order_review: '待评价',
  me_order_refund: '退款/售后',
  me_stat_fav: '收藏',
  me_stat_follow_shop: '订阅店铺',
  me_stat_footprint: '足迹',
  me_stat_coupons: '红包卡券',
  me_vip_title: '88VIP · 尊享九大权益',
  me_vip_sub: '天天领补贴 · 专享95折',
} as const;
