import { NavigationDeclaration } from './navigation.types';

export const NAVIGATION_DECLARATION = {
  app: 'douyin',
  routes: [
    {
      path: '/',
      component: 'HomePage',
      params: {},
      entryPoint: 'home',
      scrollContainers: [
        { name: 'video-feed', direction: 'vertical', description: '抖音推荐短视频上下滑流' },
        { name: 'comments-list', direction: 'vertical', description: '视频评论列表' },
      ],
      uiStates: [
        {
          id: 'home.base',
          search: {},
          description: '抖音推荐短视频流默认态',
          actions: [
            {
              id: 'home.video.like.toggle',
              label: '点赞或取消点赞当前视频',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'home.video.star.toggle',
              label: '收藏或取消收藏当前视频',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'home.author.follow.toggle',
              label: '关注或取消关注作者',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'home.caption.expand.toggle',
              label: '展开或收起视频文案',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'home.fullscreen.mode.toggle',
              label: '切换全屏观看模式',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
          ],
        },
        {
          id: 'home.sheet.comments',
          search: { sheet: 'comments' },
          description: '抖音视频评论半屏面板',
          actions: [
            {
              id: 'home.comment.input.change',
              label: '输入评论内容',
              behavior: 'input',
              paramsSchema: { value: 'string' },
            },
            {
              id: 'home.comment.submit',
              label: '发送评论',
              behavior: 'submit',
            },
            {
              id: 'home.comment.like.toggle',
              label: '点赞或取消点赞单条评论',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { commentId: 'string', to: 'boolean' },
            },
          ],
        },
      ],
      queryParams: { tab: 'string' },
      description: '抖音首页推荐流',
    },
    {
      path: '/friends',
      component: 'FriendsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'friends-list', direction: 'vertical', description: '朋友动态列表' },
      ],
      uiStates: [
        {
          id: 'friends.base',
          search: {},
          description: '朋友页默认',
          actions: [
            {
              id: 'friends.item.follow.toggle',
              label: '回关或取消关注朋友',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { friendId: 'string', to: 'boolean' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '抖音朋友页',
    },
    {
      path: '/publish',
      component: 'PublishPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'publish-main', direction: 'vertical', description: '发布作品表单' },
      ],
      uiStates: [
        {
          id: 'publish.base',
          search: {},
          description: '发布作品默认',
          actions: [
            {
              id: 'publish.caption.change',
              label: '输入作品描述文案',
              behavior: 'input',
              paramsSchema: { value: 'string' },
            },
            {
              id: 'publish.work.submit',
              label: '发布抖音作品',
              behavior: 'submit',
            },
          ],
        },
      ],
      queryParams: {},
      description: '发布作品页',
    },
    {
      path: '/messages',
      component: 'MessagesPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'messages-list', direction: 'vertical', description: '抖音消息列表' },
      ],
      uiStates: [
        {
          id: 'messages.base',
          search: {},
          description: '抖音消息中心默认',
          actions: [
            {
              id: 'messages.all.read',
              label: '全部标为已读',
              behavior: 'other',
            },
            {
              id: 'messages.item.read',
              label: '点击阅读单条消息',
              behavior: 'other',
              scope: 'item',
              paramsSchema: { id: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '抖音消息页',
    },
    {
      path: '/me',
      component: 'MePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'me-main', direction: 'vertical', description: '我的个人主页内容' },
      ],
      uiStates: [
        {
          id: 'me.base',
          search: {},
          description: '我的主页默认',
        },
      ],
      queryParams: {},
      description: '抖音个人主页',
    },
    {
      path: '/creator/:id',
      component: 'CreatorProfilePage',
      params: { id: 'string' },
      entryPoint: 'none',
      scrollContainers: [
        { name: 'creator-main', direction: 'vertical', description: '创作者主页作品列表' },
      ],
      uiStates: [
        {
          id: 'creator.base',
          search: {},
          description: '创作者主页默认',
          actions: [
            {
              id: 'creator.follow.toggle',
              label: '在主页关注或取消关注创作者',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '创作者详情主页',
    },
    {
      path: '/search',
      component: 'SearchPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'search-main', direction: 'vertical', description: '抖音热榜与搜索结果' },
      ],
      uiStates: [
        {
          id: 'search.base',
          search: {},
          description: '抖音搜索默认页',
          actions: [
            {
              id: 'search.input.change',
              label: '输入抖音搜索词',
              behavior: 'input',
              paramsSchema: { value: 'string' },
            },
          ],
        },
      ],
      queryParams: { q: 'string' },
      description: '抖音搜索页',
    },
  ],
  transitions: [
    {
      id: 'tab.home',
      from: ['/friends', '/messages', '/me'],
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到首页',
      ui: { placement: 'tabbar', icon: 'home', gesture: 'tap' },
    },
    {
      id: 'tab.friends',
      from: ['/', '/messages', '/me'],
      to: '/friends',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到朋友',
      ui: { placement: 'tabbar', icon: 'friends', gesture: 'tap' },
    },
    {
      id: 'tab.publish',
      from: ['/', '/friends', '/messages', '/me'],
      to: '/publish',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开拍摄发布页',
      ui: { placement: 'tabbar', icon: 'publish', gesture: 'tap' },
    },
    {
      id: 'tab.messages',
      from: ['/', '/friends', '/me'],
      to: '/messages',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到消息',
      ui: { placement: 'tabbar', icon: 'messages', gesture: 'tap' },
    },
    {
      id: 'tab.me',
      from: ['/', '/friends', '/messages'],
      to: '/me',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到我',
      ui: { placement: 'tabbar', icon: 'me', gesture: 'tap' },
    },
    {
      id: 'home.topTab.switch',
      from: '/',
      to: '/',
      search: {},
      searchParams: { tab: 'string' },
      mode: 'replace',
      params: {},
      label: '切换顶部频道Tab',
      ui: { placement: 'topbar', icon: 'tab', gesture: 'tap' },
    },
    {
      id: 'home.search.open',
      from: '/',
      to: '/search',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开抖音搜索页',
      ui: { placement: 'topbar', icon: 'search', gesture: 'tap' },
    },
    {
      id: 'home.creator.open',
      from: ['/', '/friends'],
      to: '/creator/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '打开创作者主页',
      ui: { placement: 'content', icon: 'user', gesture: 'tap' },
      dataSource: { ref: 'friends', paramMapping: { id: 'id' }, labelField: 'name' },
    },
    {
      id: 'home.comments.open',
      from: { path: '/', search: { sheet: null } },
      to: '/',
      search: { sheet: 'comments' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开评论区半屏面板',
      ui: { placement: 'content', icon: 'comment', gesture: 'tap' },
    },
    {
      id: 'home.comments.close',
      from: { path: '/', search: { sheet: 'comments' } },
      to: '/',
      search: { sheet: null },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '关闭评论区半屏面板',
      ui: { placement: 'content', icon: 'close', gesture: 'tap' },
    },
    {
      id: 'search.submit',
      from: '/search',
      to: '/search',
      search: {},
      searchParams: { q: 'string' },
      mode: 'replace',
      params: {},
      label: '执行抖音搜索',
      ui: { placement: 'topbar', icon: 'search', gesture: 'tap' },
    },
  ],
  capabilities: {
    historyBack: true,
  },
} as const satisfies NavigationDeclaration;

export type TransitionId = (typeof NAVIGATION_DECLARATION.transitions)[number]['id'];
