import { NavigationDeclaration } from './navigation.types';

export const NAVIGATION_DECLARATION = {
  app: 'taobao',
  routes: [
    {
      path: '/',
      component: 'HomePage',
      params: {},
      entryPoint: 'home',
      scrollContainers: [
        { name: 'home-feed', direction: 'vertical', description: '淘宝首页推荐商品流' },
        { name: 'home-channels', direction: 'horizontal', description: '首页顶部频道栏' },
      ],
      uiStates: [
        {
          id: 'home.base',
          search: {},
          description: '淘宝推荐首页',
          actions: [
            {
              id: 'home.promo.claim',
              label: '领取国庆狂欢消费券',
              behavior: 'submit',
            },
          ],
        },
      ],
      queryParams: { channel: 'string' },
      description: '淘宝首页',
    },
    {
      path: '/video',
      component: 'VideoPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'video-feed', direction: 'vertical', description: '淘宝视频逛逛内容流' },
      ],
      uiStates: [
        {
          id: 'video.base',
          search: {},
          description: '淘宝视频页默认',
          actions: [
            {
              id: 'video.item.like.toggle',
              label: '点赞或取消点赞视频',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { videoId: 'string', to: 'boolean' },
            },
            {
              id: 'video.item.follow.toggle',
              label: '关注或取消关注达人',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { videoId: 'string', to: 'boolean' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '淘宝视频页',
    },
    {
      path: '/messages',
      component: 'MessagesPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'messages-list', direction: 'vertical', description: '消息通知列表' },
      ],
      uiStates: [
        {
          id: 'messages.base',
          search: {},
          description: '消息中心默认',
          actions: [
            {
              id: 'messages.all.read',
              label: '全部标为已读',
              behavior: 'other',
            },
            {
              id: 'messages.item.read',
              label: '查看并标记单条消息已读',
              behavior: 'other',
              scope: 'item',
              paramsSchema: { id: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '淘宝消息页',
    },
    {
      path: '/cart',
      component: 'CartPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'cart-list', direction: 'vertical', description: '购物车商品列表' },
      ],
      uiStates: [
        {
          id: 'cart.base',
          search: {},
          description: '购物车默认',
          actions: [
            {
              id: 'cart.item.select.toggle',
              label: '勾选或取消勾选购物车商品',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { productId: 'string', to: 'boolean' },
            },
            {
              id: 'cart.item.qty.change',
              label: '修改购物车商品数量',
              behavior: 'other',
              scope: 'item',
              paramsSchema: { productId: 'string', delta: 'number' },
            },
            {
              id: 'cart.selectAll.toggle',
              label: '全选或取消全选购物车',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'cart.checkout.submit',
              label: '结算购物车商品',
              behavior: 'submit',
            },
          ],
        },
      ],
      queryParams: {},
      description: '淘宝购物车页',
    },
    {
      path: '/me',
      component: 'MePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'me-main', direction: 'vertical', description: '我的淘宝个人中心' },
      ],
      uiStates: [
        {
          id: 'me.base',
          search: {},
          description: '我的淘宝默认',
        },
      ],
      queryParams: {},
      description: '我的淘宝',
    },
    {
      path: '/product/:id',
      component: 'ProductDetailPage',
      params: { id: 'string' },
      entryPoint: 'none',
      scrollContainers: [
        { name: 'product-detail', direction: 'vertical', description: '宝贝详情内容' },
      ],
      uiStates: [
        {
          id: 'product.detail.base',
          search: {},
          description: '宝贝详情默认',
          actions: [
            {
              id: 'product.favorite.toggle',
              label: '收藏或取消收藏宝贝',
              behavior: 'toggle',
              paramsSchema: { productId: 'string', to: 'boolean' },
            },
            {
              id: 'product.cart.add',
              label: '将宝贝加入购物车',
              behavior: 'submit',
              paramsSchema: { productId: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '宝贝详情页',
    },
    {
      path: '/search',
      component: 'SearchPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'search-results', direction: 'vertical', description: '搜索结果列表' },
      ],
      uiStates: [
        {
          id: 'search.base',
          search: {},
          description: '搜索默认页',
          actions: [
            {
              id: 'search.input.change',
              label: '输入搜索关键词',
              behavior: 'input',
              paramsSchema: { value: 'string' },
            },
            {
              id: 'search.history.clear',
              label: '清空历史搜索',
              behavior: 'other',
            },
          ],
        },
      ],
      queryParams: { q: 'string' },
      description: '商品搜索页',
    },
  ],
  transitions: [
    {
      id: 'tab.home',
      from: ['/video', '/messages', '/cart', '/me'],
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到首页',
      ui: { placement: 'tabbar', icon: 'home', gesture: 'tap' },
    },
    {
      id: 'tab.video',
      from: ['/', '/messages', '/cart', '/me'],
      to: '/video',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到视频',
      ui: { placement: 'tabbar', icon: 'video', gesture: 'tap' },
    },
    {
      id: 'tab.messages',
      from: ['/', '/video', '/cart', '/me'],
      to: '/messages',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到消息',
      ui: { placement: 'tabbar', icon: 'message', gesture: 'tap' },
    },
    {
      id: 'tab.cart',
      from: ['/', '/video', '/messages', '/me'],
      to: '/cart',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到购物车',
      ui: { placement: 'tabbar', icon: 'cart', gesture: 'tap' },
    },
    {
      id: 'tab.me',
      from: ['/', '/video', '/messages', '/cart'],
      to: '/me',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到我的淘宝',
      ui: { placement: 'tabbar', icon: 'me', gesture: 'tap' },
    },
    {
      id: 'home.channel.switch',
      from: '/',
      to: '/',
      search: {},
      searchParams: { channel: 'string' },
      mode: 'replace',
      params: {},
      label: '切换首页顶部频道',
      ui: { placement: 'topbar', icon: 'channel', gesture: 'tap' },
    },
    {
      id: 'home.search.open',
      from: '/',
      to: '/search',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开搜索页',
      ui: { placement: 'topbar', icon: 'search', gesture: 'tap' },
    },
    {
      id: 'home.product.open',
      from: ['/', '/video', '/cart', '/me', '/search'],
      to: '/product/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '打开宝贝详情',
      ui: { placement: 'content', icon: 'product', gesture: 'tap' },
      dataSource: { ref: 'products', paramMapping: { id: 'id' }, labelField: 'title' },
    },
    {
      id: 'search.submit',
      from: '/search',
      to: '/search',
      search: {},
      searchParams: { q: 'string' },
      mode: 'replace',
      params: {},
      label: '执行商品搜索',
      ui: { placement: 'topbar', icon: 'search', gesture: 'tap' },
    },
    {
      id: 'product.cart.open',
      from: '/product/:id',
      to: '/cart',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '从详情页前往购物车',
      ui: { placement: 'content', icon: 'cart', gesture: 'tap' },
    },
  ],
  capabilities: {
    historyBack: true,
  },
} as const satisfies NavigationDeclaration;

export type TransitionId = (typeof NAVIGATION_DECLARATION.transitions)[number]['id'];
