import type { strings } from './strings';

export const stringsEn: Record<keyof typeof strings, string> = {
  app_name: 'Douyin',
  top_hot: 'Hot',
  top_follow: 'Following',
  top_live_badge: 'LIVE',
  top_groupbuy: 'Deals',
  top_city: 'Nearby',
  top_mall: 'Shop',
  top_recommend: 'For You',
  fullscreen_watch: 'Full Screen',
  exit_fullscreen: 'Exit Full Screen',
  caption_expand: 'More',
  caption_collapse: 'Less',
  tab_home: 'Home',
  tab_friends: 'Friends',
  tab_messages: 'Inbox',
  tab_me: 'Me',
  comments_title: ' comments',
  comment_placeholder: 'Add a nice comment...',
  comment_send: 'Send',
  friends_title: 'Friends Feed',
  friends_follow_btn: 'Follow Back',
  friends_followed_btn: 'Friends',
  publish_title: 'New Post',
  publish_caption_placeholder: 'Describe your video and add hashtags...',
  publish_submit_btn: 'Post Video',
  publish_success_toast: 'Video published successfully!',
  messages_title: 'Inbox',
  messages_mark_read: 'Read All',
  me_likes_label: 'Likes',
  me_following_label: 'Following',
  me_followers_label: 'Followers',
  me_edit_profile: 'Edit Profile',
  me_tab_works: 'Videos',
  me_tab_liked: 'Liked',
  me_tab_saved: 'Saved',
  creator_follow: '+ Follow',
  creator_followed: 'Following',
  search_placeholder: 'South Gate Boss Menswear',
  search_btn: 'Search',
  search_hot_title: 'Trending on Douyin',
};
