export const strings = {
  app_name: '抖音',
  top_hot: '热点',
  top_follow: '关注',
  top_live_badge: '直播',
  top_groupbuy: '团购',
  top_city: '同城',
  top_mall: '商城',
  top_recommend: '推荐',
  fullscreen_watch: '全屏观看',
  exit_fullscreen: '退出全屏',
  caption_expand: '展开',
  caption_collapse: '收起',
  tab_home: '首页',
  tab_friends: '朋友',
  tab_messages: '消息',
  tab_me: '我',
  comments_title: '条评论',
  comment_placeholder: '善语结善缘，恶言伤人心',
  comment_send: '发送',
  friends_title: '朋友动态',
  friends_follow_btn: '回关',
  friends_followed_btn: '互相关注',
  publish_title: '发布作品',
  publish_caption_placeholder: '添加作品描述，带话题 #男装人的国庆八天乐 让更多人看到...',
  publish_submit_btn: '发布抖音',
  publish_success_toast: '作品已成功发布！',
  messages_title: '消息',
  messages_mark_read: '全部已读',
  me_likes_label: '获赞',
  me_following_label: '关注',
  me_followers_label: '粉丝',
  me_edit_profile: '编辑资料',
  me_tab_works: '作品',
  me_tab_liked: '喜欢',
  me_tab_saved: '收藏',
  creator_follow: '+ 关注',
  creator_followed: '已关注',
  search_placeholder: '南门张老板 男装穿搭',
  search_btn: '搜索',
  search_hot_title: '抖音热榜',
} as const;
