import type { strings } from './strings';

export const stringsEn: Record<keyof typeof strings, string> = {
  app_name: 'Meituan',
  tab_home: 'For You',
  tab_video: 'Video',
  tab_xiaotuan: 'Xiaotuan',
  tab_cart: 'Cart',
  tab_me: 'Me',
  location_default: 'Huawei Xi’an R&D Center',
  location_alt: 'Grand Tang Mall Xi’an',
  search_placeholder: 'McDonald’s',
  search_btn: 'Search',
  kk_waimai: 'Delivery',
  kk_groupon: 'Groupon',
  kk_hotel: 'Hotels',
  kk_instashop: 'InstaShop',
  kk_medicine: 'Pharmacy',
  kk_xiaoxiang: 'Xiaoxiang',
  kk_food: 'Dining',
  kk_leisure: 'Leisure',
  kk_travel: 'Attractions',
  kk_movie: 'Movies',
  kk_loan: 'Credit',
  kk_massage: 'Spa',
  kk_errand: 'Errands',
  kk_fruit: 'Free Fruit',
  kk_more: 'More',
  badge_buy_gift: 'Free Gift',
  badge_food_fest: 'Food Fest',
  promo_tejiatuan_title: 'Super Deals',
  promo_tejiatuan_sub: 'Daily Low Prices',
  promo_xiaoxiang_title: 'Xiaoxiang Mart',
  promo_xiaoxiang_self: 'Meituan Direct',
  promo_xiaoxiang_slogan: 'Fresh Grocery & Daily Essentials',
  promo_xiaoxiang_speed: 'In 30 Mins',
  promo_xiaoxiang_store: 'Xiaoxiang Mart - Yanta Jinye Station',
  promo_xiaoxiang_freight: 'Free Delivery',
  promo_xiaoxiang_sales: '630k+ Sold/Mo',
  currency_symbol: '¥',
  search_history_title: 'Search History',
  search_discover_title: 'Discover',
  search_clear: 'Clear',
  search_no_results: 'No matching deals found',
  detail_title: 'Deal Detail',
  detail_guarantee: 'Anytime Refund · Auto Refund on Expiry · Verified Merchant',
  detail_validity: 'Valid for 90 days after purchase · Available on weekends',
  detail_reviews_title: 'Reviews (999+)',
  detail_shop_enter: 'Visit Store',
  detail_shop: 'Merchant',
  detail_fav: 'Save',
  detail_faved: 'Saved',
  detail_add_cart: 'Add to Cart',
  detail_added_cart: 'Added',
  detail_buy_now: 'Buy Now',
  cart_title: 'Cart',
  cart_empty: 'Your cart is empty',
  cart_select_all: 'All',
  cart_total: 'Total:',
  cart_checkout: 'Checkout',
  cart_checked_out_toast: 'Order placed! Vouchers added to your wallet',
  video_title: 'Meituan Video',
  video_follow_btn: 'Follow',
  video_followed_btn: 'Following',
  xiaotuan_title: 'Xiaotuan AI Guide',
  xiaotuan_subtitle: 'Your Local Dining & Lifestyle Assistant',
  xiaotuan_greeting: 'Hi! I am Xiaotuan AI. Looking for great food or hotels near Huawei Xi’an R&D?',
  me_orders_title: 'My Orders',
  me_orders_all: 'All Orders',
  me_order_unpaid: 'To Pay',
  me_order_unused: 'To Use',
  me_order_review: 'To Review',
  me_order_refund: 'Refunds',
  me_stat_fav: 'Saved',
  me_stat_follow_shop: 'Followed',
  me_stat_footprint: 'History',
  me_stat_coupons: 'Coupons',
  me_vip_title: 'Meituan VIP · Citywide Perks',
  me_vip_sub: 'Up to ¥20 Off Expansion Coupons',
};
