export const strings = {
  app_name: '美团',
  tab_home: '推荐',
  tab_video: '视频',
  tab_xiaotuan: '小团',
  tab_cart: '购物车',
  tab_me: '我的',
  location_default: '华为西安研究所',
  location_alt: '西安大唐不夜城',
  search_placeholder: '麦当劳',
  search_btn: '搜索',
  kk_waimai: '外卖',
  kk_groupon: '团购',
  kk_hotel: '酒店民宿',
  kk_instashop: '闪购',
  kk_medicine: '看病买药',
  kk_xiaoxiang: '小象超市',
  kk_food: '美食',
  kk_leisure: '休闲玩乐',
  kk_travel: '景点游玩',
  kk_movie: '电影演出',
  kk_loan: '借钱',
  kk_massage: '按摩足疗',
  kk_errand: '跑腿',
  kk_fruit: '免费水果',
  kk_more: '更多服务',
  badge_buy_gift: '买就送',
  badge_food_fest: '逛吃节',
  promo_tejiatuan_title: '特价团',
  promo_tejiatuan_sub: '天天有低价',
  promo_xiaoxiang_title: '小象超市',
  promo_xiaoxiang_self: '美团自营',
  promo_xiaoxiang_slogan: '生鲜零食百货一站购',
  promo_xiaoxiang_speed: '最快30分钟',
  promo_xiaoxiang_store: '小象超市(原美团买菜)-雁塔锦业站',
  promo_xiaoxiang_freight: '新客0运费',
  promo_xiaoxiang_sales: '月售63万+',
  currency_symbol: '¥',
  search_history_title: '历史搜索',
  search_discover_title: '猜你想搜',
  search_clear: '清空',
  search_no_results: '未找到相关团购或商户，换个词试试吧',
  detail_title: '团购详情',
  detail_guarantee: '随时退 · 过期自动退 · 到店吃 · 美团放心消费',
  detail_validity: '有效期: 购买后90天内有效 · 周末节假日通用',
  detail_reviews_title: '网友评价 (999+)',
  detail_shop_enter: '进店看看',
  detail_shop: '商户',
  detail_fav: '收藏',
  detail_faved: '已收藏',
  detail_add_cart: '加入购物车',
  detail_added_cart: '已加购',
  detail_buy_now: '立即抢购',
  cart_title: '购物车',
  cart_empty: '购物车空空如也，去首页看看特价团吧',
  cart_select_all: '全选',
  cart_total: '合计:',
  cart_checkout: '去结算',
  cart_checked_out_toast: '抢购成功！团购券已发放至【我的】券包',
  video_title: '美团视频 · 种草官',
  video_follow_btn: '关注',
  video_followed_btn: '已关注',
  xiaotuan_title: '小团 AI 帮找',
  xiaotuan_subtitle: '吃喝玩乐本地向导 · 随时问我',
  xiaotuan_greeting: '嗨！我是美团 AI 助手小团，在华为西安研究所附近想吃点什么或去哪玩？',
  me_orders_title: '我的订单',
  me_orders_all: '全部订单',
  me_order_unpaid: '待付款',
  me_order_unused: '待使用',
  me_order_review: '待评价',
  me_order_refund: '退款/售后',
  me_stat_fav: '收藏',
  me_stat_follow_shop: '关注店铺',
  me_stat_footprint: '足迹',
  me_stat_coupons: '红包卡券',
  me_vip_title: '美团神会员 · 吃喝玩乐全城通用',
  me_vip_sub: '神券膨胀最高立减20元 · 特价团折上折',
} as const;
