import { NavigationDeclaration } from './navigation.types';

export const NAVIGATION_DECLARATION = {
  app: 'meituan',
  routes: [
    {
      path: '/',
      component: 'HomePage',
      params: {},
      entryPoint: 'home',
      scrollContainers: [
        { name: 'home-feed', direction: 'vertical', description: '美团推荐首页内容流' },
      ],
      uiStates: [
        {
          id: 'home.base',
          search: {},
          description: '美团推荐首页',
          actions: [
            {
              id: 'home.location.switch',
              label: '切换当前定位地址',
              behavior: 'toggle',
            },
          ],
        },
      ],
      queryParams: { category: 'string' },
      description: '美团首页',
    },
    {
      path: '/video',
      component: 'VideoPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'video-feed', direction: 'vertical', description: '美团视频种草流' },
      ],
      uiStates: [
        {
          id: 'video.base',
          search: {},
          description: '美团视频页默认',
          actions: [
            {
              id: 'video.item.like.toggle',
              label: '点赞或取消点赞视频',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { videoId: 'string', to: 'boolean' },
            },
            {
              id: 'video.item.follow.toggle',
              label: '关注或取消关注探店达人',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { videoId: 'string', to: 'boolean' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '美团视频页',
    },
    {
      path: '/xiaotuan',
      component: 'XiaotuanPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'xiaotuan-chat', direction: 'vertical', description: '小团 AI 助手对话流' },
      ],
      uiStates: [
        {
          id: 'xiaotuan.base',
          search: {},
          description: '小团 AI 助手默认页',
          actions: [
            {
              id: 'xiaotuan.topic.select',
              label: '向小团发送快捷提问',
              behavior: 'other',
              scope: 'item',
              paramsSchema: { topicId: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '美团小团 AI 页',
    },
    {
      path: '/cart',
      component: 'CartPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'cart-list', direction: 'vertical', description: '购物车团购列表' },
      ],
      uiStates: [
        {
          id: 'cart.base',
          search: {},
          description: '购物车默认',
          actions: [
            {
              id: 'cart.item.select.toggle',
              label: '勾选或取消勾选购物车团购',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { dealId: 'string', to: 'boolean' },
            },
            {
              id: 'cart.item.qty.change',
              label: '修改购物车团购数量',
              behavior: 'other',
              scope: 'item',
              paramsSchema: { dealId: 'string', delta: 'number' },
            },
            {
              id: 'cart.selectAll.toggle',
              label: '全选或取消全选购物车',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'cart.checkout.submit',
              label: '结算购物车商品',
              behavior: 'submit',
            },
          ],
        },
      ],
      queryParams: {},
      description: '美团购物车页',
    },
    {
      path: '/me',
      component: 'MePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'me-main', direction: 'vertical', description: '我的美团个人中心' },
      ],
      uiStates: [
        {
          id: 'me.base',
          search: {},
          description: '我的美团默认',
        },
      ],
      queryParams: {},
      description: '我的美团',
    },
    {
      path: '/deal/:id',
      component: 'DealDetailPage',
      params: { id: 'string' },
      entryPoint: 'none',
      scrollContainers: [
        { name: 'deal-detail', direction: 'vertical', description: '团购/商户详情内容' },
      ],
      uiStates: [
        {
          id: 'deal.detail.base',
          search: {},
          description: '团购详情默认',
          actions: [
            {
              id: 'deal.favorite.toggle',
              label: '收藏或取消收藏团购',
              behavior: 'toggle',
              paramsSchema: { dealId: 'string', to: 'boolean' },
            },
            {
              id: 'deal.cart.add',
              label: '将团购加入购物车',
              behavior: 'submit',
              paramsSchema: { dealId: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '团购详情页',
    },
    {
      path: '/search',
      component: 'SearchPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'search-results', direction: 'vertical', description: '搜索结果列表' },
      ],
      uiStates: [
        {
          id: 'search.base',
          search: {},
          description: '搜索默认页',
          actions: [
            {
              id: 'search.input.change',
              label: '输入搜索关键词',
              behavior: 'input',
              paramsSchema: { value: 'string' },
            },
            {
              id: 'search.history.clear',
              label: '清空历史搜索',
              behavior: 'other',
            },
          ],
        },
      ],
      queryParams: { q: 'string' },
      description: '美团搜索页',
    },
  ],
  transitions: [
    {
      id: 'tab.home',
      from: ['/video', '/xiaotuan', '/cart', '/me'],
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到推荐',
      ui: { placement: 'tabbar', icon: 'home', gesture: 'tap' },
    },
    {
      id: 'tab.video',
      from: ['/', '/xiaotuan', '/cart', '/me'],
      to: '/video',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到视频',
      ui: { placement: 'tabbar', icon: 'video', gesture: 'tap' },
    },
    {
      id: 'tab.xiaotuan',
      from: ['/', '/video', '/cart', '/me'],
      to: '/xiaotuan',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到小团',
      ui: { placement: 'tabbar', icon: 'xiaotuan', gesture: 'tap' },
    },
    {
      id: 'tab.cart',
      from: ['/', '/video', '/xiaotuan', '/me'],
      to: '/cart',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到购物车',
      ui: { placement: 'tabbar', icon: 'cart', gesture: 'tap' },
    },
    {
      id: 'tab.me',
      from: ['/', '/video', '/xiaotuan', '/cart'],
      to: '/me',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到我的',
      ui: { placement: 'tabbar', icon: 'me', gesture: 'tap' },
    },
    {
      id: 'home.category.switch',
      from: '/',
      to: '/',
      search: {},
      searchParams: { category: 'string' },
      mode: 'replace',
      params: {},
      label: '切换首页金刚区分类',
      ui: { placement: 'content', icon: 'category', gesture: 'tap' },
    },
    {
      id: 'home.search.open',
      from: '/',
      to: '/search',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开搜索页',
      ui: { placement: 'topbar', icon: 'search', gesture: 'tap' },
    },
    {
      id: 'home.deal.open',
      from: ['/', '/video', '/xiaotuan', '/cart', '/me', '/search'],
      to: '/deal/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '打开团购或商户详情',
      ui: { placement: 'content', icon: 'deal', gesture: 'tap' },
      dataSource: { ref: 'deals', paramMapping: { id: 'id' }, labelField: 'title' },
    },
    {
      id: 'search.submit',
      from: '/search',
      to: '/search',
      search: {},
      searchParams: { q: 'string' },
      mode: 'replace',
      params: {},
      label: '执行商户团购搜索',
      ui: { placement: 'topbar', icon: 'search', gesture: 'tap' },
    },
    {
      id: 'deal.cart.open',
      from: '/deal/:id',
      to: '/cart',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '从详情页前往购物车',
      ui: { placement: 'content', icon: 'cart', gesture: 'tap' },
    },
  ],
  capabilities: {
    historyBack: true,
  },
} as const satisfies NavigationDeclaration;

export type TransitionId = (typeof NAVIGATION_DECLARATION.transitions)[number]['id'];
