export const strings = {
  app_name: '拼多多',
  tab_home: '首页',
  tab_video: '多多视频',
  tab_promo: '国庆立减',
  tab_chat: '聊天',
  tab_me: '个人中心',
  ch_recommend: '推荐',
  ch_phone: '手机',
  ch_food: '食品',
  ch_medical: '医药',
  ch_women: '女装',
  ch_department: '百货',
  ch_shoes_bags: '鞋包',
  search_placeholder: '数据线快充超快闪充',
  search_btn: '搜索',
  pxq_title: '拼小圈',
  pxq_subtitle: '查看好友动态',
  pxq_viewed_subtitle: '已查看好友最新拼单动态',
  kk_seckill: '限时秒杀',
  kk_topup: '充值中心',
  kk_wheel: '现金大转盘',
  kk_fruit: '免费领水果',
  kk_other: '其他',
  ddmc_title: '多多买菜',
  subsidy_title: '百亿补贴',
  subsidy_coupon_150: '150元券',
  currency_symbol: '¥',
  search_history_title: '历史搜索',
  search_discover_title: '搜索发现',
  search_clear: '清空',
  search_no_results: '未找到相关商品，换个词试试吧',
  detail_title: '商品详情',
  detail_guarantee: '假一赔十 · 全场包邮 · 七天无理由退货 · 极速退款',
  detail_shipping: '极速发货 · 承诺48小时内发货 · 退货包运费',
  detail_reviews_title: '商品评价 (999+)',
  detail_shop_enter: '进店逛逛',
  detail_shop: '店铺',
  detail_fav: '收藏',
  detail_faved: '已收藏',
  detail_share: '分享',
  detail_buy_alone: '单独购买',
  detail_group_buy: '发起拼单',
  detail_group_joined: '拼单成功',
  promo_page_title: '国庆立减 · 百亿补贴专场',
  promo_page_sub: '官方补贴 · 买贵必赔 · 全场立减',
  promo_claim_btn: '领取150元国庆补贴券',
  promo_claimed_btn: '已领取150元补贴券',
  chat_title: '聊天',
  chat_all_read: '全部标为已读',
  video_title: '多多视频',
  video_follow_btn: '关注',
  video_followed_btn: '已关注',
  me_orders_title: '我的订单',
  me_orders_all: '查看全部',
  me_order_unpaid: '待付款',
  me_order_grouping: '待分享',
  me_order_unshipped: '待发货',
  me_order_shipped: '待收货',
  me_order_review: '待评价',
  me_stat_coupons: '优惠券',
  me_stat_fav: '商品收藏',
  me_stat_follow_shop: '店铺关注',
  me_stat_footprint: '历史浏览',
  me_vip_title: '省钱月卡 · 尊享百亿补贴特权',
  me_vip_sub: '每周领无门槛神券 · 买贵双倍赔',
} as const;
