import type { strings } from './strings';

export const stringsEn: Record<keyof typeof strings, string> = {
  app_name: 'Pinduoduo',
  tab_home: 'Home',
  tab_video: 'Duoduo Video',
  tab_promo: 'Holiday Sale',
  tab_chat: 'Chat',
  tab_me: 'Profile',
  ch_recommend: 'For You',
  ch_phone: 'Phones',
  ch_food: 'Food',
  ch_medical: 'Health',
  ch_women: 'Women',
  ch_department: 'Daily',
  ch_shoes_bags: 'Shoes & Bags',
  search_placeholder: 'Fast Charging Cable',
  search_btn: 'Search',
  pxq_title: 'Pin Moments',
  pxq_subtitle: 'View friend updates',
  pxq_viewed_subtitle: 'Viewed latest friend updates',
  kk_seckill: 'Flash Sale',
  kk_topup: 'Top-up',
  kk_wheel: 'Cash Wheel',
  kk_fruit: 'Free Fruit',
  kk_other: 'More',
  ddmc_title: 'Duoduo Grocery',
  subsidy_title: '10B Subsidy',
  subsidy_coupon_150: '¥150 Off',
  currency_symbol: '¥',
  search_history_title: 'Search History',
  search_discover_title: 'Discover',
  search_clear: 'Clear',
  search_no_results: 'No matching items found',
  detail_title: 'Item Detail',
  detail_guarantee: '10x Fake Compensation · Free Shipping · 7-Day Return',
  detail_shipping: 'Fast Dispatch · Ships within 48h · Free Return Shipping',
  detail_reviews_title: 'Reviews (999+)',
  detail_shop_enter: 'Visit Store',
  detail_shop: 'Store',
  detail_fav: 'Save',
  detail_faved: 'Saved',
  detail_share: 'Share',
  detail_buy_alone: 'Buy Alone',
  detail_group_buy: 'Team Purchase',
  detail_group_joined: 'Joined Team',
  promo_page_title: 'Holiday Sale · 10B Subsidy',
  promo_page_sub: 'Official Subsidy · Best Price Guarantee',
  promo_claim_btn: 'Claim ¥150 Holiday Coupon',
  promo_claimed_btn: 'Claimed ¥150 Coupon',
  chat_title: 'Chat',
  chat_all_read: 'Mark All Read',
  video_title: 'Duoduo Video',
  video_follow_btn: 'Follow',
  video_followed_btn: 'Following',
  me_orders_title: 'My Orders',
  me_orders_all: 'View All',
  me_order_unpaid: 'To Pay',
  me_order_grouping: 'To Share',
  me_order_unshipped: 'To Ship',
  me_order_shipped: 'To Receive',
  me_order_review: 'To Review',
  me_stat_coupons: 'Coupons',
  me_stat_fav: 'Saved',
  me_stat_follow_shop: 'Stores',
  me_stat_footprint: 'History',
  me_vip_title: 'Monthly Saver Card · 10B Perks',
  me_vip_sub: 'Weekly Coupons · Price Match Guarantee',
};
