import { NavigationDeclaration } from './navigation.types';

export const NAVIGATION_DECLARATION = {
  app: 'baidunetdisk',
  routes: [
    {
      path: '/',
      component: 'HomePage',
      params: {},
      entryPoint: 'home',
      scrollContainers: [
        { name: 'home-feed', direction: 'vertical', description: '百度网盘首页主内容流' },
        { name: 'home-transfers', direction: 'horizontal', description: '首页转存记录横向卡片流' },
        { name: 'home-memories', direction: 'horizontal', description: '首页回忆精选横向卡片流' },
      ],
      uiStates: [
        {
          id: 'home.base',
          search: {},
          description: '百度网盘首页默认态',
          actions: [
            {
              id: 'home.transfer.tab.switch',
              label: '切换转存记录或订阅更新标签',
              behavior: 'other',
              paramsSchema: { tab: 'string' },
            },
            {
              id: 'home.privacy.toggle',
              label: '切换首页模块隐私隐藏状态',
              behavior: 'toggle',
              paramsSchema: { section: 'string', to: 'boolean' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '百度网盘首页',
    },
    {
      path: '/files',
      component: 'FilesPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'files-list', direction: 'vertical', description: '网盘文件列表' },
      ],
      uiStates: [
        {
          id: 'files.base',
          search: {},
          description: '网盘文件列表页默认态',
          actions: [
            {
              id: 'files.item.star.toggle',
              label: '星标或取消星标文件',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { fileId: 'string', to: 'boolean' },
            },
          ],
        },
      ],
      queryParams: { category: 'string' },
      description: '百度网盘文件页',
    },
    {
      path: '/ai',
      component: 'KukuAiPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'ai-chat', direction: 'vertical', description: '库库AI智能助手对话流' },
      ],
      uiStates: [
        {
          id: 'ai.base',
          search: {},
          description: '库库AI助手页默认态',
          actions: [
            {
              id: 'ai.prompt.ask',
              label: '向库库AI发送预设指令',
              behavior: 'submit',
              scope: 'item',
              paramsSchema: { promptId: 'string' },
            },
            {
              id: 'ai.history.clear',
              label: '清空库库AI对话记录',
              behavior: 'other',
            },
          ],
        },
      ],
      queryParams: {},
      description: '百度网盘库库AI页',
    },
    {
      path: '/share',
      component: 'SharePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'share-list', direction: 'vertical', description: '共享群组与文件流' },
      ],
      uiStates: [
        {
          id: 'share.base',
          search: {},
          description: '共享频道默认态',
          actions: [
            {
              id: 'share.all.read',
              label: '全部共享消息标为已读',
              behavior: 'other',
            },
            {
              id: 'share.group.read',
              label: '查看并标记共享群组消息已读',
              behavior: 'other',
              scope: 'item',
              paramsSchema: { id: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '百度网盘共享页',
    },
    {
      path: '/me',
      component: 'MePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'me-main', direction: 'vertical', description: '我的个人中心内容流' },
      ],
      uiStates: [
        {
          id: 'me.base',
          search: {},
          description: '我的个人中心默认态',
        },
      ],
      queryParams: {},
      description: '百度网盘我的页面',
    },
    {
      path: '/file/:id',
      component: 'FileDetailPage',
      params: { id: 'string' },
      entryPoint: 'none',
      scrollContainers: [
        { name: 'file-detail', direction: 'vertical', description: '文件详情与预览内容' },
      ],
      uiStates: [
        {
          id: 'file.detail.base',
          search: {},
          description: '文件详情默认态',
          actions: [
            {
              id: 'file.star.toggle',
              label: '收藏或取消收藏文件',
              behavior: 'toggle',
              paramsSchema: { fileId: 'string', to: 'boolean' },
            },
            {
              id: 'file.download.trigger',
              label: '下载或转存文件到本地传输列表',
              behavior: 'submit',
              paramsSchema: { fileId: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '网盘文件详情页',
    },
    {
      path: '/search',
      component: 'SearchPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'search-results', direction: 'vertical', description: '网盘文件搜索结果流' },
      ],
      uiStates: [
        {
          id: 'search.base',
          search: {},
          description: '文件搜索页默认态',
          actions: [
            {
              id: 'search.input.change',
              label: '输入网盘文件搜索关键词',
              behavior: 'input',
              paramsSchema: { value: 'string' },
            },
            {
              id: 'search.history.clear',
              label: '清空历史搜索记录',
              behavior: 'other',
            },
          ],
        },
      ],
      queryParams: { q: 'string' },
      description: '网盘文件搜索页',
    },
  ],
  transitions: [
    {
      id: 'tab.home',
      from: ['/files', '/ai', '/share', '/me'],
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到首页',
      ui: { placement: 'tabbar', icon: 'home', gesture: 'tap' },
    },
    {
      id: 'tab.files',
      from: ['/', '/ai', '/share', '/me'],
      to: '/files',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到文件',
      ui: { placement: 'tabbar', icon: 'files', gesture: 'tap' },
    },
    {
      id: 'tab.ai',
      from: ['/', '/files', '/share', '/me'],
      to: '/ai',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到库库AI',
      ui: { placement: 'tabbar', icon: 'ai', gesture: 'tap' },
    },
    {
      id: 'tab.share',
      from: ['/', '/files', '/ai', '/me'],
      to: '/share',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到共享',
      ui: { placement: 'tabbar', icon: 'share', gesture: 'tap' },
    },
    {
      id: 'tab.me',
      from: ['/', '/files', '/ai', '/share'],
      to: '/me',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到我的',
      ui: { placement: 'tabbar', icon: 'me', gesture: 'tap' },
    },
    {
      id: 'home.search.open',
      from: ['/', '/files'],
      to: '/search',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开文件搜索页',
      ui: { placement: 'topbar', icon: 'search', gesture: 'tap' },
    },
    {
      id: 'home.category.open',
      from: '/',
      to: '/files',
      search: {},
      searchParams: { category: 'string' },
      mode: 'replace',
      params: {},
      label: '从首页金刚区打开对应分类文件',
      ui: { placement: 'content', icon: 'folder', gesture: 'tap' },
    },
    {
      id: 'files.category.switch',
      from: '/files',
      to: '/files',
      search: {},
      searchParams: { category: 'string' },
      mode: 'replace',
      params: {},
      label: '切换文件页分类筛选',
      ui: { placement: 'topbar', icon: 'filter', gesture: 'tap' },
    },
    {
      id: 'file.detail.open',
      from: ['/', '/files', '/ai', '/share', '/me', '/search'],
      to: '/file/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '打开网盘文件或文件夹详情',
      ui: { placement: 'content', icon: 'file', gesture: 'tap' },
      dataSource: { ref: 'files', paramMapping: { id: 'id' }, labelField: 'title' },
    },
    {
      id: 'search.submit',
      from: '/search',
      to: '/search',
      search: {},
      searchParams: { q: 'string' },
      mode: 'replace',
      params: {},
      label: '执行文件搜索',
      ui: { placement: 'topbar', icon: 'search', gesture: 'tap' },
    },
    {
      id: 'file.ai.analyze',
      from: '/file/:id',
      to: '/ai',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '使用库库AI分析当前文件',
      ui: { placement: 'content', icon: 'ai', gesture: 'tap' },
    },
  ],
  capabilities: {
    historyBack: true,
  },
} as const satisfies NavigationDeclaration;

export type TransitionId = (typeof NAVIGATION_DECLARATION.transitions)[number]['id'];
